config/routes.rb
Rails.application.routes.draw do

  resources :drugs, only: [ :index, :show ]
  resources :assays, only: [:index]

end

app/models/assay.rb
require 'open-uri'

class Assay
  attr_accessor :assay_id
  attr_reader :description

  def initialize assay_id, description
    self.assay_id = assay_id
    self.description = description
  end

  def Assay.search(target_name)
    pchem_result = open("https://pubchem.ncbi.nlm.nih.gov/rest/pug/assay/target/proteinname/#{target_name}/JSON")
    pchem = JSON.parse(pchem_result.read)

    pchem["PC_AssayContainer"].map do |assay|
      assay_id = assay["assay"]["descr"]["aid"]["id"]
      assay_descr = assay["assay"]["descr"]["description"]
      Assay.new(assay_id, assay_descr)
    end
  end

  def fetch_compounds
    cids_file = open("https://pubchem.ncbi.nlm.nih.gov/rest/pug/assay/aid/#{assay_id}/cids/JSON")
    cids = JSON.parse(cids_file.read)
    cids["InformationList"]["Information"][0]["CID"].map do |cid|
      Compound.new(cid)
    end
  end
end

app/models/compound.rb
class Compound
  attr_accessor :cid

  def initialize cid
    self.cid = cid
  end

  def fetch_drug
    property_file = open("https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/#{cid}/property/MolecularFormula,MolecularWeight,CanonicalSMILES,IUPACName,XLogP,ExactMass,MonoisotopicMass,TPSA,Complexity,Charge,HBondDonorCount,HBondAcceptorCount,RotatableBondCount,HeavyAtomCount,IsotopeAtomCount,AtomStereoCount,DefinedAtomStereoCount,UndefinedAtomStereoCount,BondStereoCount,DefinedBondStereoCount,UndefinedBondStereoCount,CovalentUnitCount,Volume3D,XStericQuadrupole3D,YStericQuadrupole3D,ZStericQuadrupole3D,FeatureCount3D,FeatureAcceptorCount3D,FeatureDonorCount3D,FeatureAnionCount3D,FeatureCationCount3D,FeatureRingCount3D,FeatureHydrophobeCount3D,ConformerModelRMSD3D,EffectiveRotorCount3D,ConformerCount3D,Fingerprint2D/JSON")
    properties = JSON.parse(property_file.read)
    Drug.new(properties["PropertyTable"]["Properties"])
  end
end

app/models/drug.rb
require 'open-uri'
require 'json'

class Drug
	attr_accessor :properties

	def initialize(properties)
		self.properties = properties
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/assays_controller.rb
class AssaysController < ApplicationController

  def index
    if params[:target_name].nil?
      render :search
      return
    end

    @assays=Assay.search(params[:target_name])
  end
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  def index
    assay_id = params["assay_id"]
    ...
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/assays/index.html.erb
<h1> Results</h1>
<ul>
  <% for assay in @assays do %>
    <li>
      <%= assay.description %>
	  </li>
    <li>
      <%= link_to assay.assay_id.to_string, drugs_index_path %>
    </li>
    <br/>
  <% end %>
</ul>

app/views/assays/search.html.erb
<h1>Search page</h1>
<h2>You can search here a protein name to retrieve potential drugs assay and related informations</h2>

<div><%= form_tag(@drugs, method: "get") do |f| %>
      <%= text_field_tag :target_name, params[:target_name] %>
      <%= submit_tag "Search", :target_name => nil %>
	<% end %>
</div>

app/views/assays/show.html.erb
<h1>More info</h1>

<ul>
	<% for property in @res do %>
	<li><%= property %></li>
	<% end %>
</ul>

app/views/drugs/index.html.erb
<h1> Results</h1>
<ul>
  <% for result in @drugs["PC_AssayContainer"] do %>
    <li>
    <%= result["assay"]["descr"]["description"] %>
	</li>
   <li>
    <%= result["assay"]["descr"]["aid"]["id"] %>
   </li>
   <br/>
   <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Genephar2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>